[package]
name = "flash_lender"
version = "0.0.1"
edition = "2024.alpha"

[dependencies]
Mgo = { git = "https://github.com/MangoNetworkOs/Mango.git", subdir = "crates/mgo-framework/packages/mgo-framework", rev = "framework/devnet" }

[addresses]
flash_lender = "0x0"