[package]
name = "Coins"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Mgo = { git = "https://github.com/MangoNetworkOs/Mango.git", subdir = "crates/mgo-framework/packages/mgo-framework", rev = "framework/devnet" }

[addresses]
examples = "0x0"